- bullet-train.zsh-theme
A white status foreground is more readable on my screen on both red and green backgrounds.
> Sets status fg to white by default

- bullet-train.zsh-theme
When pressing tab on an incomplete command like `l` or `c` the commandline
turns and stays green so even the output is colored green or the
highlight of the suggestions swaps colors when tabbing through.
This happens only if the `zsh-syntax-highlighting` plugin is not enabled (unlike shown in 
demo `.gif`).
I fixed this by adding the missing `%f` in `prompt_char()`.
> Fixed highlighting on tab completion (without `zsh-syntax-highlighting`)

- bullet-train.zsh-theme
> Testing npm without leting which and type output escape

- README.md
- bullet-train.zsh-theme
This patch adds support for three display modes of the path in the prompt via the BULLETTRAIN_DIR_EXTENDED variable:
* `0`: short path - just the current directory name
* `1`: medium path - the current directory path with up to three elements after which the path gets short with an ellipsis (default)
* `2`: long path - the full path is shown, `$HOME` is abbreviated with `~`
Also see pull-request https://github.com/caiogondim/bullet-train-oh-my-zsh-theme/pull/54 for reference where I screwed up a little ;)
> Add support for three display modes of the path in the prompt: short, medium and long

- README.md
Adding hint for Ubuntu (and variants) users which ttf package will help them to see the unicode fonts right.
> Adding valuable info to README

- bullet-train.zsh-theme
Hey, an unmatched quote was causing an error on startup:
```bash
if [[ $BULLETTRAIN_PROMPT_SEPARATE_LINE == false  ]]; then
bt_prompt_char=" ${bt_prompt_char}
fi
```
to:
```bash
if [[ $BULLETTRAIN_PROMPT_SEPARATE_LINE == false  ]]; then
bt_prompt_char="${bt_prompt_char}"
fi
```
so I fixed it. I'm not very well versed in bash, but it did the trick for me. Any problems let me know. 
Thanks, 
Nick.
> Fix unmatched quote

- bullet-train.zsh-theme
and thus added the %{%}-delimiters around the `prompt_line_sep` whitespace.
Works for me and fixes #80
> I took a look at this answer http://unix.stackexchange.com/a/90876

- bullet-train.zsh-theme
Feel free to close but I think the prompt is more user-friendly when the CWD is in a predictable location. This change will also move the dev-specific segments (ruby/virtualenv/nvm/go) closer to the git segment. What do you think?
> Move path before dev-specific segments; dev segments closer to git

- bullet-train.zsh-theme
This way each part of the $PROMPT is only coded once, so bugfixes won't need to be repeated 3 times.
> DRY $PROMPT

- bullet-train.zsh-theme
This way the user can differentiate between system and nvm node versions, similar to the virtualenv segment.
> Use "nvm current" to display node version

- bullet-train.zsh-theme
This PR fixes a chruby output bug. Currently, it looks like this:
https://s3.amazonaws.com/f.cl.ly/items/1O390u2W0j3j1O2x2q05/Screen%20Shot%202015-11-22%20at%2011.45.27%20PM.png
If you have say 3 rubies installed, the sed command only replaces the ` * ` prefix on the selected chruby version, but doesn't strip out the other rubies installed. This PR only prints the matching line with an active ruby.
> Fix chruby support by only printing the line of the matched ruby

- bullet-train.zsh-theme
pyenv allows us to link multiple versions to the same environment.
Instead of 
we display this
> Allow multiple versions of Python to be displayed on one line

- README.md
- bullet-train.zsh-theme
display a yellow background color to visualize git repo dirty state is useful, I know there's this `✘` symbol that does the same thing, but sometimes there can be too many symbols around and one can miss the cross, and push their code by mistake.
I think with this feature introduced (borrowed), one can better work with `git push` because it's more visual significance when it's OK to push.
https://gist.github.com/agnoster/3712874#file-agnoster-zsh-theme-L82
> add BULLETTRAIN_GIT_COLORIZE_DIRTY to show yellow BG when in dirty state

- bullet-train.zsh-theme
This gives us ability to use string substitution for changing e.g. how
branch name is displayed.
This was in my local changes for some time. I am using git flow with default feature prefix "feature/". This does not look good with bullet-train prompt. So, this feature gives us ability to change:
to:
----
This implementation allows user to specify git prompt command. By default we set it to ```git_prompt_info```. As this isn't the actual execution of command, we need to delay variable/function extending, thus ``\${git_prompt_info}``.
So, in case showed on screens this would be 
``` bash
BULLETTRAIN_GIT_PROMPT_CMD=\${\$(git_prompt_info)//\\//\ \ }
```
Please note, that we still need to *delay* variable expansion, so we need to escape all *weird* character - **$**, **\**, **\<space>**, etc. …
> Allow settings custom git prompt

- bullet-train.zsh-theme
This PR eliminates double space in front of the `$` character at the end of the prompt which appears only if `BULLETTRAIN_PROMPT_SEPARATE_LINE="false"`.
> Eliminating double space if prompt on one line

- README.md
For zgen users one needs to invoke `zgen oh-my-zsh` before loading this theme. Fixes #126
> Update README for zgen users

- README.md
- bullet-train.zsh-theme
Instead of returning if nvm is not present, get version information from node itself.
> Use node to get version information if nvm is not present. Fixes #132

- bullet-train.zsh-theme
Conditional operator [[ ]] tests files and strings. To test error codes
returned from command, use if statement directly without any operators.
Credits: @abalabahaha
> Fix for parse error - Issue #134

- bullet-train.zsh-theme
Closes https://github.com/caiogondim/bullet-train-oh-my-zsh-theme/issues/138
> Display exec time as something like 2d3h31m5s instead of 185465s

- README.md
- bullet-train.zsh-theme
This commit removes all `_SHOW` variables for showing/hiding segments. Now `Hg/Mercurial` completely disappears  - should I also remove (now empty) variable table from README?
Two remaining *SHOWs* are:
* `BULLETTRAIN_STATUS_EXIT_SHOW` - we may consider changing this from **boolean** into **enum**, as described in #179.
* `BULLETTRAIN_DIR_CONTEXT_SHOW`
What about default `BULLETTRAIN_PROMPT_ORDER` variable? Should I change it to conform default `_SHOW`s? Or, as this is anyway quite invasive change, we can leave it by? 
Any suggestions are welcome :smile:
> close #186: Remove redundant *_SHOW* variables

- bullet-train.zsh-theme
Since the latest version after the $ / # a space is missing
> Add space after the prompt (\$)

- README.md
- bullet-train.zsh-theme
Currently, when handling large git repositories on weak machines, generating the prompt can be really slow. For most oh-my-zsh themes, a good workaround is to manually set the "oh-my-zsh.hide-status" git config flag, which causes the `git_prompt_info` function to do nothing.
However, bullet-train does some extra work besides calling `git_prompt_info`. Therefore, setting this flag causes the git part of the prompt to be only partially hidden, and there is still an annoying delay. This should be fixed.
I have tested this fix successfully on my machines, and the check is basically the same as in Oh My Zsh (see https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/git.zsh#L4).
> Hide git prompt completely if git config flag "oh-my-zsh.hide-status" is set

- bullet-train.zsh-theme
```
go 1.7
```
instead of
```
go  1.7
```
> Remove extra space in go prompt

- bullet-train.zsh-theme
In the PR #162, the final space after the prompt chars was removed. This PR is bringing it back.
> Bringing back the final prompt chars space

- bullet-train.zsh-theme
Add space after `BULLETTRAIN_PROMPT_CHAR` only if it's non empty. When it's empty, it looks better because there's no extra spaces at the end of the prompt.
> Add space only if non-empty BULLETTRAIN_PROMPT_CHAR

- README.md
- bullet-train.zsh-theme
This PR adds a Kubernetes context segment.
It requires the user to at least set `BULLETTRAIN_KCTX_KCONFIG` to a valid kubeconfig location (e.g. `/Users/<username>/.kube/config` on OSX) and have `kubectl` installed.
Other variables supported (with default values):
```
BULLETTRAIN_KCTX_BG # Background color, default: yellow
BULLETTRAIN_KCTX_FG # Foreground color, default: white
BULLETTRAIN_KCTX_PREFIX # Segment prefix, default: ⎈
```
Example:
> Adds a Kubernetes Context Segment

- bullet-train.zsh-theme
Go has bumped its version to 1.10 months ago. The `grep` code in script can only get one digit of minor version, showing `1.1` for version 1.10.
> Update Go version segment

- bullet-train.zsh-theme
Fixed open comment from https://github.com/caiogondim/bullet-train.zsh/pull/224/commits/cc57e991d95c5c464a2a8cfc6074e908e961ccd2?utf8=%E2%9C%93&diff=unified&w=1
> Make python env show only when not the default.
